interface=eth0

# --- IPv4 Configuration (DHCPv4) ---
# Give out IPv4 addresses, the IPv4 router (gateway), and the IPv4 DNS
dhcp-range=192.168.100.10, 192.168.100.100, 24h
dhcp-option=option:router, 192.168.100.1
dhcp-option=option:dns-server, 8.8.8.8

# --- IPv6 Configuration (SLAAC + Stateless DHCPv6) ---
# Enable Router Advertisements for SLAAC, and pass the IPv6 DNS/Domain
enable-ra
dhcp-range=2001:DB8:FEDE:1::, ra-stateless, 64
dhcp-option=option6:dns-server, [2001:4860:4860::8888]
dhcp-option=option6:domain-search, netsec.local
