interface eth0 {
    send ia-na 0;    # Ask for a normal IP address for eth0
    send ia-pd 0;    # Ask for the Prefix Delegation for the LANs
};

id-assoc na 0 {
    # This just tells dhcp6c to accept the address the ISP gives it for eth0
};

id-assoc pd 0 {
    prefix-interface eth1 {
        sla-id 1;
        sla-len 8;
    };
    prefix-interface eth2 {
        sla-id 2;
        sla-len 8;
    };
};
