# Listen only on the LAN interfaces
interface=eth1
interface=eth2

# Enable Router Advertisements
enable-ra

# The "constructor" dynamically looks at eth1 and eth2. 
# Whatever Global Unicast Address it finds there, it will advertise that prefix via SLAAC (ra-only).
dhcp-range=::,constructor:eth1,ra-only,64
dhcp-range=::,constructor:eth2,ra-only,64
