# The start and end of the IP lease block (the last IP is for r1)
start 192.168.100.17
end   192.168.100.29

# The interface that udhcpd will use
interface eth0

# Options
opt dns 1.1.1.1 8.8.8.8
opt subnet 255.255.255.240
opt router 192.168.100.30
